version: '3.8'

services:
  go-api:
    build: .
    ports:
      - 3003:3003
    depends_on:
      - db
    extends:
      file: ../base.yaml
      service: base
    volumes:
      - .:/usr/src/app
    command: go run ./cmd/bench/main.go