[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "~0.13.4"
tokio = { version = "0.2", features = ["full"] }
pretty_env_logger = "0.4"
futures = "0.3.0"
queryst = "1"
